<a href="https://colab.research.google.com/github/Vitalyastiy/statistics/blob/main/.AB-coursera.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Пример а/б - теста. Курсера

In [2]:
# %%
# держатъ под контролем значимостъ и корректироватъ одним из методов
'''Процедура множественного тестирования'''
import numpy  as np
import pandas as pd
from scipy  import stats
import seaborn  as sns
import matplotlib.pyplot  as plt 
plt.style.use('ggplot')
%matplotlib inline
'''n-упоминания, m-смерти'''
n_st = 70
m_st = 25
n_lan = 38
m_lan = 7 
n_gr = 41 
m_gr = 12
n_nw = 105
m_nw = 41
alpha = 0.05
# %%
m_st/n_st, m_lan/n_lan, m_gr/n_gr, m_nw/n_nw 


(0.35714285714285715,
 0.18421052631578946,
 0.2926829268292683,
 0.3904761904761905)

In [3]:
# %%
from statsmodels.stats.proportion import proportions_ztest
_, p1 = proportions_ztest((m_st, m_lan), (n_st, n_lan), \
value=0, alternative='larger')

_, p2 = proportions_ztest((m_st, m_gr), (n_st, n_gr), \
value=0, alternative='larger')

_, p3 = proportions_ztest((m_st, m_nw), (n_st, n_nw), \
value=0, alternative='larger')

pval = np.array([p1, p2, p3])
pval # pval = 0.05

array([0.03008672, 0.24343199, 0.67209806])

In [4]:
pval >0.05/3 # корректировка Бенфирони, делим на количество тестов 

array([ True,  True,  True])

In [5]:
# Поправка на value  Бенферони
from statsmodels.sandbox.stats.multicomp import multipletests
rejected, p_corrected, _, _ = multipletests(pval, alpha = 0.05, method = 'bonferroni')
p_corrected

array([0.09026015, 0.73029598, 1.        ])

In [6]:
# Поправка на value  Холма, повышаем мощностъ теста
from statsmodels.sandbox.stats.multicomp import multipletests
rejected, p_corrected, _, _ = multipletests(pval, alpha = 0.05, method = 'holm')
p_corrected

array([0.09026015, 0.48686399, 0.67209806])

In [7]:
# Поправка на value  Хохберга
from statsmodels.sandbox.stats.multicomp import multipletests
rejected, p_corrected, _, _ = multipletests(pval, alpha = 0.05, method = 'fdr_bh')
p_corrected

array([0.09026015, 0.36514799, 0.67209806])